# yaml-language-server: $schema=https://restk.ai/schema/v1/request.schema.json
# Restk Request

id: "322065319612907546"
version: 1
name: GET_environment-variable-substitution
method: GET
url: '{{base_url}}/get'
sortOrder: 56
description: ""
folderId: "322065319604518918"
parameters: []
headers:
    - id: "969B0CC1-FEEF-49A3-8034-42EA215F9137"
      key: X-Token
      value: '{{bearer_token}}'
      isEnabled: true
      isSecret: false
      order: 0
bodyType: none
bodyContentType: ""
bodyData: ""
authType: jwt
isAuthOverridden: true
authConfigData: |-
    {
      "jwtAlgorithm": "HS256",
      "jwtHeaderName": "Authorization",
      "jwtPayload": "{\n  \"name\": \"Vinay KD\"\n}",
      "jwtPrefix": "Bearer",
      "jwtSecret": "{{REDACTED}}"
    }
prescript: ""
postscript: ""
skipParentScripts: false
variables: []
