# yaml-language-server: $schema=https://restk.ai/schema/v1/request.schema.json
# Restk Request

id: "325310386385453083"
version: 1
name: 5. List Active Settings
method: GET
url: '{{base_url}}/api/v0/admin/logs/active'
sortOrder: 4
description: ""
folderId: "325310386385453079"
parameters: []
headers: []
bodyType: none
bodyContentType: ""
bodyData: ""
authType: bearer
isAuthOverridden: true
authConfigData: |-
    {
      "bearerToken": "{{REDACTED}}"
    }
prescript: ""
postscript: ""
skipParentScripts: false
variables: []
